### ISSUE TITLE
Agree technical approach for Subsites upgrade

### ISSUE THREAD

**Issue by willguv** [localgovdrupal/localgov_subsites#135]
We need to review the way H&F architected its Subsite Homepage, Menus and Theming and agree an approach for Essex/ a submission to LGD

**Comment by willguv** [comment]
@justinepocock can you paste in the relevant notes you made please? Thanks

**Comment by justinepocock** [comment]
Not the best notes in the world but I got down that: 

The deliverable could be:

- A new thing which needs migrating 
- A new thing only available to new LGD builds
- Module that provides extra Subsites functionality - which just needs to be turned on

### Colours
Consider using taxonomy as a dropdown instead of a text field so councils can rename the labels. 

If you want more than X colours - speak to a dev

### Menus
Use multiple menus instead of one large menu 
There's a hook in the module which reads the menu structure and that powers the colour changing on child pages. 
Need to look at events/news/blog pages that aren't in the menu and how they inherit the correct colours - directories does this https://www.lbhf.gov.uk/living-independently/living-independently-service-directory but H&F don't have news/events/blogs in a subsite currently.

(events channels is probably the answer here)

**Comment by justinepocock** [comment]
Just putting important things from our channel into here. 

https://github.com/wearechicken/localgov_menu_subsites/ 

I've just stuck it on our github account for the moment. I'll move it over to the real localgov account once we're happy it's doing what we want :slightly_smiling_face:
[11:24](https://localgovdrupal.slack.com/archives/C065WA56DEF/p1701948284733119)
Instructions are there in the README for how to set it up and use it. I've managed to set it up on a plain LGD3 install, and it works using the existing subsite overview page as a subsite.
[11:25](https://localgovdrupal.slack.com/archives/C065WA56DEF/p1701948346650899)
Subsite pages are a little annoying to use with this, as they have that required field to choose the parent subsite that we don't actually need now. So you can either stop that being required, take the field out or just not use that content type. (We don't use it.)
[11:27](https://localgovdrupal.slack.com/archives/C065WA56DEF/p1701948448861359)
There's no style or anything themey in there yet. This is just all the backend parts of it. It'll put the right classes on the body tag for the subsite and lets the menu appear, but doing the theming's up to you for now.

I've tried to make it flexible enough that it can work with either the existing subsites content types, or ones you set up yourself. The first is because Mark asked for it to work with the existing subsite overview page, and the second is because that's what H&F does.
[9:05](https://localgovdrupal.slack.com/archives/C065WA56DEF/p1702026306455529)
We could feasibly write an upgrade path from one to the other, too.
[9:06](https://localgovdrupal.slack.com/archives/C065WA56DEF/p1702026399552789)
IE we could automate adding all the existing subsite pages into the menu, then taking away the fields that localgov_subsites uses that get in the way of localgov_menu_subsites.

**Comment by andybroomfield** [comment]
Is the intention to have subsites_menu as a new sub module, or integrate this so that subsites are primarly driven by the menu system? I'm just concerned on this being a major change that it does not break and maintains compatability with existing subsites.

**Comment by justinepocock** [comment]
We're going for an entirely optional sub module so that we don't break all your stuffs :)

**Comment by willguv** [comment]
Oh lovely!

**Comment by justinepocock** [comment]
Next steps: 

@rupertj to:

- [x] Make a real project for it called Subsites Extras 
- [ ] Create a subsite menu on install for people to use instead of main menu 

@justinepocock and @markconroy to look at creating a new region in the base theme for the menu to sit 

@willguv will tell @FinnERLewis it's coming to a tech meeting soon... but I guess I just did that ;)

**Comment by willguv** [comment]
Thanks @justinepocock !

**Comment by justinepocock** [comment]
A real module is now made. 

Ru will made a video to show people how to use this.
