### ISSUE TITLE
Subsite overview page needs a parent field

### ISSUE THREAD

**Issue by willguv** [localgovdrupal/localgov_subsites#148]
In https://github.com/localgovdrupal/localgov/issues/487 we made parent field location and labelling consistent 

We need to ensure the same with Subsite overview pages. They should have a parent field:

- At the top of the description tab
- Labelled 'parent page'

This is quite urgent as two new councils (Essex and Dumfries) are starting to use subsites heavily this month

**Comment by markconroy** [comment]
@willguv what content types should the subsite overview be able to set as its parent? Currently subsite pages have a parent field, set to subsite overviews and other subsite pages.

Also, is the issue here that breadcrumbs are not showing on subsite overview pages? That is probably because the URL for subsite overviews pages is just website.com/node-title - so it's usually a top level page. To fix this, it might be better to just update the URL patterns for subsite overview pages to follow the menu structure, like we do with other content types. Then, if a subsite overview page gets put into the menu under "Births, deaths and marriages", it's URL will become website.com/births-deaths-marriages/node-title (and the breadcrumbs should show up accordingly).

===
Thanks to [Big Blue Door](https://www.bigbluedoor.net/) for sponsoring my time to work on this.

**Comment by willguv** [comment]
I've seen content designers want to put subsites within a services structure, linking from subsite landing and sub landing pages

Following the menu patterns elsewhere seems like a good idea. I'm assuming they could still live at Home > Subsite if required?

**Comment by markconroy** [comment]
Thanks Will. 

I'm finishing up for today, but will try look at this again tomorrow.

**Comment by stephen-cox** [comment]
Just been adjusting how this working in Guides and Step by step.

To use the same pattern for subsites, there should be a services parent field in `config/optional`, which is then added to the node edit form at install time. This is just to be sure that services is enabled before adding it to the form.

Happy to pick this up if it's easier.

**Comment by markconroy** [comment]
@stephen-cox Yes please do pick this up, I think you might be a little quicker working on this than me. Thanks a lot.

**Comment by stephen-cox** [comment]
Fix for this here #151
